# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNTBridgingDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNTBridgingDemo
  pod 'JWPlayer-SDK', '~> 3.0'
  
  target 'RNTBridgingDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNTBridgingDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end